### ISSUE TITLE
[help wanted] Make snap with bluetooth for Ubuntu Core 20.04 on Raspberry Pi 4

### ISSUE THREAD

**Issue by Rturoz** [RPi-Distro/pi-bluetooth#31]
Hi,
i'm trying to do a [snap](https://snapcraft.io/docs/creating-a-snap "search") for Ubuntu Core 20.04.3 that must run on a Raspberry Pi 4 Model B. This snap is based on a python script that use the python library ['bleak'](https://bleak.readthedocs.io/en/latest/ "search"). When i run the snap on Ubuntu desktop there isn't problem. The problem is when i try to run the snap on Ubuntu Core 20.04 because there is the following error:
```
OSError: [Errno 8] Exec format error: 'bluetoothctl'.
```
I understood that to use the bluetooth on Ubuntu Core with the Raspberry Pi i must use the pi-bluetooth snap, but i don't know how to use this with my snap. More precisely, I don't know how to make my snap in such a way as to be able to use bluetooth on the Raspberry Pi.

This is my current snapcraft file to realize the snap: 
```
name: iot-band
base: core20 
version: '1.0' 
summary: Iot band app
description: |
  Iot band app

grade: devel 
confinement: devmode 

architectures:
  - build-on: amd64
    run-on: arm64

apps:
  iot-band:
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages/iot-band
    command: bin/iot_band.py
    plugs:
      - bluez
    
parts:
  iot-band:
    # See 'snapcraft plugins'
    source: .
    plugin: python
    python-packages:
      - .
  bluez:
    plugin: nil
    stage-snaps: [bluez]

```

How can i realize correctly the snap (using the "snap pi-bluetooth") to resolve this problem with the bluetooth?
